<a href="https://colab.research.google.com/github/thiagovolpolini-art/analise-clientes-banco/blob/main/analise_clientes_banco.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
tabela = pd.read_csv("ClientesBanco.csv" , encoding="latin1")
display(tabela)

,CLIENTNUM,Categoria,Idade,Sexo,Dependentes,Educação,Estado Civil,Faixa Salarial Anual,Categoria Cartão,Meses como Cliente,...,Inatividade 12m,Contatos 12m,Limite,Limite Consumido,Limite Disponível,Mudanças Transacoes_Q4_Q1,Valor Transacoes 12m,Qtde Transacoes 12m,Mudança Qtde Transações_Q4_Q1,Taxa de Utilização Cartão
0,768805383,Cliente,45,M,3,Ensino Médio,Casado,$60K - $80K,Blue,39,...,1,3,12691.0,777,11914.0,1335.000,1144,42,1625.000,0.061
1,818770008,Cliente,49,F,5,Ensino Superior,Solteiro,Less than $40K,Blue,44,...,1,2,8256.0,864,7392.0,1541.000,1291,33,3714.000,0.105
2,713982108,Cliente,51,M,3,Ensino Superior,Casado,$80K - $120K,Blue,36,...,1,0,3418.0,0,3418.0,2594.000,1887,20,2333.000,0.000
3,769911858,Cliente,40,F,4,Ensino Médio,Não informado,Less than $40K,Blue,34,...,4,1,3313.0,2517,796.0,1405.000,1171,20,2333.000,0.760
4,709106358,Cliente,40,M,3,Sem ensino formal,Casado,$60K - $80K,Blue,21,...,1,0,4716.0,0,4716.0,2175.000,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,Cliente,50,M,2,Ensino Superior,Solteiro,$40K - $60K,Blue,40,...,2,3,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462
10123,710638233,Cancelado,41,M,2,Não informado,Divorciado,$40K - $60K,Blue,25,...,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10124,716506083,Cancelado,44,F,1,Ensino Médio,Casado,Less than $40K,Blue,36,...,3,4,5409.0,0,5409.0,0.819,10291,60,0.818,0.000
10125,717406983,Cancelado,30,M,2,Ensino Superior,Não informado,$40K - $60K,Blue,36,...,3,3,5281.0,0,5281.0,0.535,8395,62,0.722,0.000
10126,714337233,Cancelado,43,F,2,Ensino Superior,Casado,Less than $40K,Silver,25,...,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

In [9]:
tabela = tabela.dropna()
display(tabela.info())
display(tabela.describe().round(1))

<class 'pandas.core.frame.DataFrame'>
Index: 10126 entries, 0 to 10126
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   CLIENTNUM                      10126 non-null  int64
 1   Categoria                      10126 non-null  object
 2   Idade                          10126 non-null  int64
 3   Sexo                           10126 non-null  object
 4   Dependentes                    10126 non-null  int64
 5   Educação                       10126 non-null  object
 6   Estado Civil                   10126 non-null  object
 7   Faixa Salarial Anual           10126 non-null  object
 8   Categoria Cartão               10126 non-null  object
 9   Meses como Cliente             10126 non-null  int64
 10  Produtos Contratados           10126 non-null  int64
 11  Inatividade 12m                10126 non-null  int64
 12  Contatos 12m                   10126 non-null  int64
 13  Limite                         10126 non-null  float64
 14  Limite Consumido               10126 non-null  int64
 15  Limite Disponível              10126 non-null  float64
 16  Mudanças Transacoes_Q4_Q1      10126 non-null  float64
 17  Valor Transacoes 12m           10126 non-null  int64
 18  Qtde Transacoes 12m            10126 non-null  int64
 19  Mudança Qtde Transações_Q4_Q1  10126 non-null  float64
 20  Taxa de Utilização Cartão      10126 non-null  float64
dtypes: float64(5), int64(10), object(6)
memory usage: 1.7+ MB

None

,CLIENTNUM,Idade,Dependentes,Meses como Cliente,Produtos Contratados,Inatividade 12m,Contatos 12m,Limite,Limite Consumido,Limite Disponível,Mudanças Transacoes_Q4_Q1,Valor Transacoes 12m,Qtde Transacoes 12m,Mudança Qtde Transações_Q4_Q1,Taxa de Utilização Cartão
count,10126.0,10126.0,10126.0,10126.0,10126.0,10126.0,10126.0,10126.0,10126.0,10126.0,10126.0,10126.0,10126.0,10126.0,10126.0
mean,739170011.6,46.3,2.3,35.9,3.8,2.3,2.5,8632.0,1162.8,7469.2,108.7,4404.4,64.9,66.6,0.3
std,36897690.3,8.0,1.3,8.0,1.6,1.0,1.1,9089.2,815.0,9091.1,353.9,3397.2,23.5,284.0,0.3
min,708082083.0,26.0,0.0,13.0,1.0,0.0,0.0,1438.3,0.0,3.0,0.0,510.0,10.0,0.0,0.0
25%,713036489.2,41.0,1.0,31.0,3.0,2.0,2.0,2555.0,358.0,1324.2,0.6,2156.0,45.0,0.6,0.0
50%,717925645.5,46.0,2.0,36.0,4.0,2.0,2.0,4549.0,1276.0,3473.0,0.7,3899.5,67.0,0.7,0.2
75%,773132751.8,52.0,3.0,40.0,5.0,3.0,3.0,11067.8,1784.0,9860.0,0.9,4741.0,81.0,0.8,0.5
max,828343083.0,73.0,5.0,56.0,6.0,6.0,6.0,34516.0,2517.0,34516.0,3397.0,18484.0,139.0,3714.0,1.0

In [13]:
import plotly.express as px

grafico = px.histogram(tabela, x="Contatos 12m")
grafico.show()